### ISSUE TITLE
Desenvolvedor Front-End Pleno / Sênior

### ISSUE THREAD

**Issue by robertogf** [zofepod/trampos#16]
#### BeautyBrands
Av. Pedroso de Morais, 240, cj 102. São Paulo - SP
Presencial

* regime: Indiferente
* escolaridade: Indiferente
* conhecimento necessário:
  * HTML (5)
  * CSS (5)
  * Javascript (4)
    * KnockoutJs
    * jQuery
    * sass + compass
  * Ser detalhista
* conhecimento desejável:
  * SEO
  * Acessibilidade
  * Preocupação com a performance
  * Noções sobre PHP
  * Noções de Google Analytics
* benefícios
  * VT
  * VR
  * Plano de carreira com ajustes semestrais
* Remuneração: 3k ~ 4k

#### descrição

Estamos em busca de um desenvolvedor front-end que pense fora da caixa, que entende que o HTML não é só um código que precisa funcionar. Deve lembrar da acessibilidade, SEO, velocidade do site e deve ser detalhista, principalmente detalhista! O candidato vai fazer parte de uma equipe de desenvolvedores para aplicações em e-commerces, hotsites, crm's e outros.

Interessados devem enviar cv e portfólio para
roberto.gadducci@bbrands.com.br

Abraços.

**Comment by danielfilho** [comment]
a vaga é pra pleno ou sênior? não existe "pleno/sênior". e pela faixa salarial, procura um junior.

**Comment by caiogondim** [comment]
Esta vaga ainda está aberta?
