### ISSUE TITLE
Desenvolvedor Front-End Pleno

### ISSUE THREAD

**Issue by brunohstein** [zofepod/trampos#21]
#### enjoei.com
(remoto)

* regime: CLT
* conhecimento necessário:
  * html (5)
  * css (5)
    * sass
  * javascript (4)
  * responsive web design
  * git
* conhecimento desejável:
  * coffeescript
  * rails

#### descrição

estamos em busca de alguém para atuar com o desenvolvimento de novas funcionalidades, manutenção e performance do site e dos aplicativos iOS e Android (webview) do enjoei.

**Comment by danielfilho** [comment]
descontinuamos o zofe trampos, @brunohstein :(
