### ISSUE TITLE
Categorizar vagas por Cidade e/ou Estado

### ISSUE THREAD

**Issue by leobalter** [zofepod/trampos#3]

**Comment by caiogondim** [comment]
Faz sentido trabalhar nisso dado o (atual) pequeno numero de vagas?

**Comment by danielfilho** [comment]
acho que não.
a intenção do zofe trampos não é crescer, ser grande ou ser famoso.
é só postar as vagas que oferecem pra gente, e a gente julga atrativa :)

**Comment by caiogondim** [comment]
Fechando a issue, então.
